# /imports/alacritty.yml

# Full Screen
[window]
dimensions = { columns = 0, lines = 0 }
padding = { x = 0, y = 0 }
startup_mode = "Windowed"

# Font Configuration
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 14.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

# Color Scheme
[colors.primary]
background = "#1d2021"
foreground = "#d5c4a1"

[colors.normal]
black = "#1d2021"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#d5c4a1"

[colors.bright]
black = "#665c54"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#fbf1c7"

# Key Bindings
[[key_bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[key_bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[key_bindings]]
key = "Q"
mods = "Command"
action = "Quit"

[[key_bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

# Cursor
[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

# Mouse
[mouse]
hide_when_typing = true

# Shell
[shell]
program = "/bin/bash"
args = ["--login"]

# Bracketed paste
bracketed_paste = false