# Full Screen
window.dimensions.columns = 0
window.dimensions.lines = 0
window.padding.x = 0
window.padding.y = 0
window.startup_mode = "Windowed"

# Font Configuration
font.normal.family = "Fira Code Nerd Font Mono"
font.normal.style = "Regular"
font.bold.family = "Fira Code Nerd Font Mono"
font.bold.style = "Bold"
font.italic.family = "Fira Code Nerd Font Mono"
font.italic.style = "Italic"
font.size = 14.0
font.offset.x = 0
font.offset.y = 0
font.glyph_offset.x = 0
font.glyph_offset.y = 0

# Color Scheme
colors.primary.background = "#1d2021"
colors.primary.foreground = "#d5c4a1"
colors.normal.black = "#1d2021"
colors.normal.red = "#fb4934"
colors.normal.green = "#b8bb26"
colors.normal.yellow = "#fabd2f"
colors.normal.blue = "#83a598"
colors.normal.magenta = "#d3869b"
colors.normal.cyan = "#8ec07c"
colors.normal.white = "#d5c4a1"
colors.bright.black = "#665c54"
colors.bright.red = "#fb4934"
colors.bright.green = "#b8bb26"
colors.bright.yellow = "#fabd2f"
colors.bright.blue = "#83a598"
colors.bright.magenta = "#d3869b"
colors.bright.cyan = "#8ec07c"
colors.bright.white = "#fbf1c7"

# Key Bindings
key_bindings = [
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "Q", mods = "Command", action = "Quit" },
    { key = "N", mods = "Command", action = "SpawnNewInstance" },
]

# Cursor
cursor.style = "Block"
cursor.unfocused_hollow = true

# Mouse
mouse.hide_when_typing = true

# Background Opacity
background_opacity = 1.0

# Shell
shell.program = "/bin/bash"
shell.args = ["--login"]

# Bracketed paste
bracketed_paste = false